name: Triggers BK Builds
on: 
  push:
    branches: [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: "buildkite/trigger-pipeline-action@v1.3.0"
      - name: Trigger a Buildkite Build 
        env:
          BUILDKITE_API_ACCESS_TOKEN: ${{ secrets.TRIGGER_BK_BUILD_TOKEN }} 
          PIPELINE: "lzrbktest/trigger-from-gha-demo"
          BRANCH: main
          COMMIT: ${{ github.sha }}
          MESSAGE:  ":github: Triggered from GHA: ${{ github.event.head_commit.message }} "

