name: Flying Delta
on: [push]
env: 
  TRIGGER_BK_PIPELINE: lzrinc/experimental-pipeline
jobs:
  Fly-Delta:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger a Buildkite Build using ENV VARS
        uses: buildkite/trigger-pipeline-action@v1.6.0
        env:
          BUILDKITE_API_ACCESS_TOKEN:  ${{ secrets.TRIGGER_BK_BUILD_TOKEN }} 
          PIPELINE: $TRIGGER_BK_PIPELINE
          BRANCH: ${{ github.ref }}
          COMMIT: ${{ github.sha }}
          MESSAGE:  ":buildkite::github: 🚀🚀🚀 Triggered from GHA using ENV Vars: ${{ github.event.head_commit.message }}"
      - name: Trigger a Buildkite Build using Input args
        uses: buildkite/trigger-pipeline-action@v1.6.0
        with:
          buildkite-token:  ${{ secrets.TRIGGER_BK_BUILD_TOKEN }} 
          pipeline:  $TRIGGER_BK_PIPELINE     
          branch: ${{ github.ref }}
          commit: ${{ github.sha }}
          message:  ":buildkite::github: 🚀🚀🚀 Triggered from GHA using Input args: ${{ github.event.head_commit.message }}"      
          build-env-vars: '{"TRIGGERED_FROM_GHA": "true"}'
          build-meta-data: '{"FOO": "bar"}'
          ignore-pipeline-branch-filter: true
      - name: Trigger a Buildkite Build using both Env vars and Input args
        uses: buildkite/trigger-pipeline-action@v1.6.0
        with:
          pipeline:  $TRIGGER_BK_PIPELINE      
          commit: ${{ github.sha }}
          message:  ":buildkite::github: 🚀🚀🚀 Used Input args message: ${{ github.event.head_commit.message }}"      
          build-meta-data: '{"FRALALA": "LALA"}'
          ignore-pipeline-branch-filter: true
          build-env-vars: '{"ENV_VAR_FROM_INPUT": "true"}'
        env:
          BUILDKITE_API_ACCESS_TOKEN:  ${{ secrets.TRIGGER_BK_BUILD_TOKEN }} 
          BRANCH: ${{ github.ref }}
          MESSAGE:  ":buildkite::github: 🚀🚀🚀 Used ENV var MESSAGE: ${{ github.event.head_commit.message }}"
          BUILD_ENV_VARS:  '{"ENV_VAR_DEF": "true"}'
