name: Flying Delta
on: [push]
jobs:
  Fly-Delta:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger a Buildkite Build using ENV VARS
        uses: buildkite/trigger-pipeline-action@feature/support-action-inputs
        env:
          BUILDKITE_API_ACCESS_TOKEN:  ${{ secrets.TRIGGER_BK_BUILD_TOKEN }} 
          PIPELINE: "lzrbktest/trigger-from-gha-demo"
          BRANCH: ${{ github.ref }}
          COMMIT: ${{ github.sha }}
          MESSAGE:  ":buildkite::github: 🚀🚀🚀 Triggered from GHA using ENV Vars: ${{ github.event.head_commit.message }}"
      - name: Trigger a Buildkite Build using Input args
        uses: buildkite/trigger-pipeline-action@feature/support-action-inputs
        with:
          buildkite-token:  ${{ secrets.TRIGGER_BK_BUILD_TOKEN }} 
          pipeline: "lzrbktest/trigger-from-gha-demo"      
          branch: ${{ github.ref }}
          commit: ${{ github.sha }}
          message:  ":buildkite::github: 🚀🚀🚀 Triggered from GHA using Input ARgs: ${{ github.event.head_commit.message }}"      
          build-env-vars: '{"TRIGGERED_FROM_GHA": "true"}'
          build-meta-data: '{"FOO": "bar"}'
          ignore-pipeline-branch-filter: true
